spring.application.name: auth
spring.profiles.default: local
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
#spring.cloud.config.uri: http://cloud.sa.internal
---
spring.config.activate.on-profile: local
#spring.config.import: configserver:http://localhost:8888
---
spring.config.activate.on-profile: deveucentral1
#spring.config.import: configserver:http://cloud.sa.internal
